### ISSUE TITLE
[Lexer error] Attribute asssignment to a string containing "/" does not work after regular expression

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#136]
Assignment to a string containing "/" or an array does not work after regular expression.

The following piece of code cannot be lexed:

```
$packages = $operatingsystem ? {
   /(?i-mx:ubuntu|debian)/  => "apa/che2",
   /(?i-mx:ubuntu|debian)/  => [ Service ['carbon-relay'], File [ '/opt/graphite/storage'] ]
 }
```

The following piece of code cannot is properly lexed:

```
$packages = $operatingsystem ? {
   /(?i-mx:ubuntu|debian)/        => "apache2",
 }
```

```
com.sonar.sslr.api.RecognitionException: Lexer error: Unable to lex string source code "$packages = $operatingsystem ? {
   /(?i-mx:ubuntu|debian)/        => "apa/che2",
 }"
    at com.sonar.sslr.impl.Parser.parse(Parser.java:79)
    at org.sonar.sslr.internal.toolkit.SourceCodeModel.setSourceCode(SourceCodeModel.java:62)
    at org.sonar.sslr.internal.toolkit.ToolkitPresenter.onSourceCodeParseButtonClick(ToolkitPresenter.java:123)
    at org.sonar.sslr.internal.toolkit.ToolkitViewImpl$5.actionPerformed(ToolkitViewImpl.java:203)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.sonar.sslr.impl.LexerException: Unable to lex string source code "$packages = $operatingsystem ? {
   /(?i-mx:ubuntu|debian)/        => "apa/che2",
 }"
    at com.sonar.sslr.impl.Lexer.lex(Lexer.java:118)
    at com.sonar.sslr.impl.Parser.parse(Parser.java:77)
    ... 39 more
Caused by: com.sonar.sslr.impl.LexerException: Unable to lex source code at line : 2 and column : 46 in file : tests://unittest
    at com.sonar.sslr.impl.Lexer.lex(Lexer.java:142)
    at com.sonar.sslr.impl.Lexer.lex(Lexer.java:116)
    ... 40 more
Caused by: java.lang.IllegalStateException: None of the channel has been able to handle character '"' (decimal value 34) at line 2, column 46
    at org.sonar.sslr.channel.ChannelDispatcher.consume(ChannelDispatcher.java:51)
    at com.sonar.sslr.impl.Lexer.lex(Lexer.java:128)
    ... 41 more
```

**Comment by iwarapter** [comment]
The regular expression to find regular expressions is abit off :/

**Comment by racodond** [comment]
Fixed!
