### ISSUE TITLE
Make the plugin be compatible with SonarQube 5.2

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#240]
Caused by: java.lang.NoSuchMethodError: org.sonar.api.component.ResourcePerspectives.as(Ljava/lang/Class;Lorg/sonar/api/component/Component;)Lorg/sonar/api/component/Perspective;
    at com.iadams.sonarqube.puppet.checks.ProjectChecks.addIssue(ProjectChecks.java:146)
    at com.iadams.sonarqube.puppet.checks.ProjectChecks.checkTestsDirectoryPresent(ProjectChecks.java:130)
    at com.iadams.sonarqube.puppet.checks.ProjectChecks.checkTestsDirectoryPresent(ProjectChecks.java:135)
    at com.iadams.sonarqube.puppet.checks.ProjectChecks.checkTestsDirectoryPresent(ProjectChecks.java:135)
    at com.iadams.sonarqube.puppet.checks.ProjectChecks.reportProjectIssues(ProjectChecks.java:64)
    at com.iadams.sonarqube.puppet.PuppetSquidSensor.save(PuppetSquidSensor.java:125)
    at com.iadams.sonarqube.puppet.PuppetSquidSensor.analyse(PuppetSquidSensor.java:106)
    at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
    at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
    at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:98)
    at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:100)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:85)
    at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:258)
    at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:253)
    at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:100)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:85)
    at org.sonar.batch.bootstrap.GlobalContainer.executeAnalysis(GlobalContainer.java:153)
    at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:110)
    at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:76)
    at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
    ... 9 more

**Comment by racodond** [comment]
Fixed in https://github.com/iwarapter/sonar-puppet/commit/3a6412475a65ff0d91b0738576f1e633956e3cd7

**Comment by iwarapter** [comment]
I have merged, this i'll extend the functional tests to cover the various versions.

**Comment by racodond** [comment]
>  i'll extend the functional tests to cover the various versions

Good idea!

**Comment by iwarapter** [comment]
After further testing, need todo more to support 5.2

**Comment by racodond** [comment]
OK. Any detail about the other issues?

**Comment by iwarapter** [comment]
The decorator we were using for the puppet_resource metric needs to be re-implemented with a [Measure Computer](https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/ce/measure/MeasureComputer.java). I have also been cleaning out some old code thats no longer used.

**Comment by racodond** [comment]
> The decorator we were using for the puppet_resource metric needs to be re-implemented with a Measure Computer.

Yep but only when we want to make the plugin be compatible with version 5.2+. I believe that'll be when version 5.x becomes the LTS. What do you think?

> I have also been cleaning out some old code thats no longer used.

OK

**Comment by iwarapter** [comment]
This has now been resolved.
